# Generated by Django 3.2.5 on 2022-01-08 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0003_auto_20220102_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='catname',
            field=models.CharField(default=1, max_length=24),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='username',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_l', to='backend_app.article')),
                ('l_users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_l', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
