# Generated by Django 3.2.5 on 2022-01-16 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0005_article_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='com_username',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
